"""empty message

Revision ID: 01bfe4c738d6
Revises: 3b60d30d4d6c
Create Date: 2023-03-15 19:51:36.550757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01bfe4c738d6'
down_revision = '3b60d30d4d6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'texts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'texts', type_='foreignkey')
    op.drop_column('texts', 'user_id')
    # ### end Alembic commands ###
