"""empty message

Revision ID: 02ef70a3b107
Revises: 341d00ea7835
Create Date: 2023-03-28 00:53:46.670695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ef70a3b107'
down_revision = '341d00ea7835'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_tiers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_tiers_id'), 'price_tiers', ['id'], unique=False)
    op.create_index(op.f('ix_price_tiers_name'), 'price_tiers', ['name'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('price_tier_id', sa.String(), nullable=True),
    sa.Column('billed_price', sa.Float(), nullable=False),
    sa.Column('stripe_subscription_item_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['price_tier_id'], ['price_tiers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_current', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_current')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_price_tiers_name'), table_name='price_tiers')
    op.drop_index(op.f('ix_price_tiers_id'), table_name='price_tiers')
    op.drop_table('price_tiers')
    # ### end Alembic commands ###
