"""empty message

Revision ID: 05a1bbcb3596
Revises: 8534aa075072
Create Date: 2023-04-03 18:00:59.911767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a1bbcb3596'
down_revision = '8534aa075072'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_uploads', sa.Column('include_in_context',
                  sa.Boolean(), nullable=True, server_default=str(True)))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_uploads', 'include_in_context')
    # ### end Alembic commands ###
