"""empty message

Revision ID: 079c710ea245
Revises: ee130f24a9b5
Create Date: 2023-07-19 01:50:53.739529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '079c710ea245'
down_revision = 'ee130f24a9b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('google_token', sa.String(), nullable=True))
    op.alter_column('subscriptions', 'billed_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('subscriptions', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscriptions', 'stripe_subscription_item_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'stripe_subscription_item_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscriptions', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscriptions', 'billed_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('subscriptions', 'google_token')
    # ### end Alembic commands ###
