"""empty message

Revision ID: 17e9a2ea5b77
Revises: 9ab6e1541034
Create Date: 2023-05-03 19:30:43.666287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e9a2ea5b77'
down_revision = '9ab6e1541034'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bot_tools', 'bot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bot_tools', 'tool_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('user_uploads', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_uploads', 'deleted')
    op.alter_column('bot_tools', 'tool_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bot_tools', 'bot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
