"""empty message

Revision ID: 1d0156008050
Revises: 9dcaa7d86e3c
Create Date: 2023-05-09 13:36:00.123445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0156008050'
down_revision = '9dcaa7d86e3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('texts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('texts', 'deleted_at')
    op.drop_column('texts', 'deleted')
    # ### end Alembic commands ###
