"""empty message

Revision ID: 1f0356f0fed3
Revises: 572e1b994242
Create Date: 2023-05-07 19:40:01.643427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0356f0fed3'
down_revision = '572e1b994242'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('embeddings_bot_id_fkey', 'embeddings', type_='foreignkey')
    op.drop_column('embeddings', 'bot_id')
    op.add_column('texts', sa.Column('history_chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'texts', 'chats', ['history_chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'texts', type_='foreignkey')
    op.drop_column('texts', 'history_chat_id')
    op.add_column('embeddings', sa.Column('bot_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('embeddings_bot_id_fkey', 'embeddings', 'bots', ['bot_id'], ['id'])
    # ### end Alembic commands ###
