"""empty message

Revision ID: 2064e145e5d4
Revises: 74bf369babcf
Create Date: 2023-05-24 13:48:19.920849

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '2064e145e5d4'
down_revision = '74bf369babcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column(
        'vector_new', Vector(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embeddings', 'vector_new')
    # ### end Alembic commands ###
