"""empty message

Revision ID: 216f408921fb
Revises: 80594254846b
Create Date: 2023-05-29 20:26:27.800871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216f408921fb'
down_revision = '80594254846b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'deleted')
    # ### end Alembic commands ###
