"""empty message

Revision ID: 2486a8658495
Revises: 079c710ea245
Create Date: 2023-07-21 14:49:20.017052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2486a8658495'
down_revision = '079c710ea245'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'tags')
    # ### end Alembic commands ###
