"""empty message

Revision ID: 2b8c8ace3648
Revises: 17e9a2ea5b77
Create Date: 2023-05-06 01:10:34.971937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '2b8c8ace3648'
down_revision = '17e9a2ea5b77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('user_configurable', sa.Boolean()))
    # ### end Alembic commands ###

    bind = op.get_bind()
    session = orm.Session(bind = bind)

    session.execute(text("""
    UPDATE tools SET user_configurable = 'true';
    """))

    session.execute(text("""
    INSERT INTO 
        tools (name, class_name, internal_filename, description, user_configurable)
    VALUES
        ('Text Generation', 'TextGeneration', 'text_generation', 'Leverages ChatGPT to generate text or other content for the user.', 'false')
    """))

    session.execute(text("""
    UPDATE tools SET user_configurable = 'false' WHERE name = 'Respond to User';
    """))

    id = session.execute(text("SELECT id FROM tools WHERE name = 'Text Generation'")).first()[0]

    session.execute(text(f"""
    INSERT INTO bot_tools (bot_id, tool_id, enabled)
    SELECT
        id,
        {id},
        'true'
    FROM 
        bots
    """))

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'user_configurable')

    bind = op.get_bind()
    session = orm.Session(bind = bind)

    id = session.execute(text("SELECT id FROM tools WHERE name = 'Text Generation'")).first()[0]

    session.execute(text(f"DELETE FROM bot_tools WHERE tool_id = {id}"))
    session.execute(text(f"DELETE FROM tools WHERE id = {id}"))


    
    # ### end Alembic commands ###
