"""empty message

Revision ID: 341d00ea7835
Revises: 76532b7f4f59
Create Date: 2023-03-24 19:16:18.652309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341d00ea7835'
down_revision = '76532b7f4f59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_uploads', sa.Column('filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_uploads', 'filename')
    # ### end Alembic commands ###
