"""empty message

Revision ID: 3b60d30d4d6c
Revises: db09e4ed95f3
Create Date: 2023-03-15 15:06:10.726919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b60d30d4d6c'
down_revision = 'db09e4ed95f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'name')
    # ### end Alembic commands ###
