"""empty message

Revision ID: 3e3cc1f3f862
Revises: 74bf369babcf
Create Date: 2023-05-19 23:03:06.604587

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy import orm
from app.models import Text


# revision identifiers, used by Alembic.
revision = '3e3cc1f3f862'
down_revision = '74bf369babcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("embeddings", "vector")
    op.add_column("embeddings", sa.Column('vector', Vector(
                        dim=768)))
    
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    texts = session.query(Text).all()
    for t in texts:
        t.refresh_embeddings()

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("embeddings", "vector")
    op.add_column("embeddings", sa.Column('vector', Vector(
                        dim=1536), nullable=False))
    
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    texts = session.query(Text).all()
    for t in texts:
        t.refresh_embeddings()
    # ### end Alembic commands ###
