"""empty message

Revision ID: 441211d552b3
Revises: a853412c8d02
Create Date: 2023-07-21 21:21:34.040299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441211d552b3'
down_revision = 'a853412c8d02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_devices', sa.Column('last_used', sa.DateTime(), nullable=True))
    op.add_column('user_devices', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_devices', 'created_at')
    op.drop_column('user_devices', 'last_used')
    # ### end Alembic commands ###
