"""empty message

Revision ID: 46dc3fb8df05
Revises: eaebae83559d
Create Date: 2023-04-27 20:05:29.554673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from app.models import Persona, Bot


# revision identifiers, used by Alembic.
revision = '46dc3fb8df05'
down_revision = 'eaebae83559d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column(
        'initial_message', sa.String()))
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    # fill in persona initial_message
    persona = session.query(Persona).first()
    persona.initial_message = "Hello! I'm Glyph! How can I help you today?"
    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'initial_message')
    # ### end Alembic commands ###
