"""empty message

Revision ID: 572e1b994242
Revises: 2b8c8ace3648
Create Date: 2023-05-07 19:17:17.419107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572e1b994242'
down_revision = '2b8c8ace3648'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('text_id', sa.Integer(), nullable=True),
    sa.Column('include_in_context', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_texts_id'), 'bot_texts', ['id'], unique=False)
    op.add_column('texts', sa.Column('text_type', sa.String(), nullable=True))
    op.drop_constraint('user_uploads_bot_id_fkey', 'user_uploads', type_='foreignkey')
    op.drop_column('user_uploads', 'bot_id')
    op.drop_column('user_uploads', 'include_in_context')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_uploads', sa.Column('include_in_context', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('user_uploads', sa.Column('bot_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_uploads_bot_id_fkey', 'user_uploads', 'bots', ['bot_id'], ['id'])
    op.drop_column('texts', 'text_type')
    op.drop_index(op.f('ix_bot_texts_id'), table_name='bot_texts')
    op.drop_table('bot_texts')
    # ### end Alembic commands ###
