"""empty message

Revision ID: 5d83f8bbcf64
Revises: 216f408921fb
Create Date: 2023-06-21 17:26:11.349190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d83f8bbcf64'
down_revision = '216f408921fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE chat_messages ALTER COLUMN content TYPE text")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE chat_messages ALTER COLUMN content TYPE varchar(1200)")
    # ### end Alembic commands ###
