"""empty message

Revision ID: 69fe672339b6
Revises: 17e9a2ea5b77
Create Date: 2023-05-05 15:59:27.963285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69fe672339b6'
down_revision = '17e9a2ea5b77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tour_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tour_completed')
    # ### end Alembic commands ###
