"""empty message

Revision ID: 70b240cfd033
Revises: a9df356d0dbe
Create Date: 2023-09-20 19:50:20.659961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b240cfd033'
down_revision = 'a9df356d0dbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('available_in_store', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'available_in_store')
    # ### end Alembic commands ###
