"""empty message

Revision ID: 714ff4215fa9
Revises: a139df4e79d2
Create Date: 2023-05-13 20:33:48.043491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714ff4215fa9'
down_revision = 'a139df4e79d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatgpt_logs', sa.Column('text_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chatgpt_logs', 'texts', ['text_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatgpt_logs', type_='foreignkey')
    op.drop_column('chatgpt_logs', 'text_id')
    # ### end Alembic commands ###
