"""empty message

Revision ID: 74bf369babcf
Revises: a139df4e79d2
Create Date: 2023-05-14 19:36:26.314649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74bf369babcf'
down_revision = 'a139df4e79d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('avatar_location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'avatar_location')
    # ### end Alembic commands ###
