"""empty message

Revision ID: 76532b7f4f59
Revises: adab9db1738e
Create Date: 2023-03-17 14:14:40.183409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76532b7f4f59'
down_revision = 'adab9db1738e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_uploads', sa.Column('processed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_uploads', 'processed')
    # ### end Alembic commands ###
