"""empty message

Revision ID: 87a1c12d7816
Revises: 441211d552b3
Create Date: 2023-07-24 18:47:38.294690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a1c12d7816'
down_revision = '441211d552b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('tts', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'tts')
    # ### end Alembic commands ###
