"""empty message

Revision ID: 916bc5362a37
Revises: dea3b506543f
Create Date: 2023-05-01 17:27:44.510650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916bc5362a37'
down_revision = 'dea3b506543f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('auth_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'auth_provider')
    # ### end Alembic commands ###
