"""empty message

Revision ID: 9c6d411c1ec1
Revises: 70b240cfd033
Create Date: 2023-09-25 18:20:26.301060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6d411c1ec1'
down_revision = '70b240cfd033'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('index_bot_users_on_bot_id', 'bot_users', ['bot_id'], unique=False)
    op.create_index('index_bot_users_on_user_id', 'bot_users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_bot_users_on_user_id', table_name='bot_users')
    op.drop_index('index_bot_users_on_bot_id', table_name='bot_users')
    # ### end Alembic commands ###
