"""empty message

Revision ID: 9dcaa7d86e3c
Revises: d1c2a425a8bc
Create Date: 2023-05-09 13:04:28.636695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '9dcaa7d86e3c'
down_revision = 'd1c2a425a8bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('_name', sa.String(), nullable=True))
    op.add_column('texts', sa.Column('text_type', sa.String(), nullable=True))

    # ### end Alembic commands ###
    session.execute(text("""
        UPDATE texts SET text_type = 'file';
    """))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('texts', 'text_type')
    op.drop_column('texts', '_name')
    # ### end Alembic commands ###
