"""empty message

Revision ID: 9f0312338dd5
Revises: 87a1c12d7816
Create Date: 2023-07-25 18:23:51.952758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0312338dd5'
down_revision = '87a1c12d7816'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('conversation_mode', sa.Integer(), server_default='-1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'conversation_mode')
    # ### end Alembic commands ###
