"""empty message

Revision ID: a139df4e79d2
Revises: 1d0156008050
Create Date: 2023-05-10 14:07:04.411652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a139df4e79d2'
down_revision = '1d0156008050'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('current_window_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('current_window_end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'current_window_end_date')
    op.drop_column('subscriptions', 'current_window_start_date')
    # ### end Alembic commands ###
