"""empty message

Revision ID: a95891948b01
Revises: 916bc5362a37
Create Date: 2023-05-01 19:06:44.551984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95891948b01'
down_revision = '916bc5362a37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_authentications', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('tool_authentications', sa.Column('refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_authentications', 'refresh_token')
    op.drop_column('tool_authentications', 'access_token')
    # ### end Alembic commands ###
