"""empty message

Revision ID: a9df356d0dbe
Revises: 9f0312338dd5
Create Date: 2023-09-05 14:35:23.224201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9df356d0dbe'
down_revision = '9f0312338dd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'description')
    # ### end Alembic commands ###
