"""empty message

Revision ID: ab1600dfe724
Revises: 02ef70a3b107
Create Date: 2023-03-28 01:20:45.011667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1600dfe724'
down_revision = '02ef70a3b107'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'deleted_at')
    # ### end Alembic commands ###
