"""empty message

Revision ID: aed47ca0d5c0
Revises: fdf4d2303bcb
Create Date: 2023-04-25 01:35:01.856145

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = 'aed47ca0d5c0'
down_revision = 'fdf4d2303bcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column(
        'sharing_enabled', sa.Boolean(), nullable=True))
    op.add_column('bots', sa.Column(
        'sharing_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'bots', ['sharing_code'])
    op.alter_column('embeddings', 'vector',
                    existing_type=Vector(1536),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embeddings', 'vector',
                    existing_type=Vector(1536),
                    nullable=True)
    op.drop_constraint(None, 'bots', type_='unique')
    op.drop_column('bots', 'sharing_code')
    op.drop_column('bots', 'sharing_enabled')
    # ### end Alembic commands ###
