"""empty message

Revision ID: d1c2a425a8bc
Revises: 2b8c8ace3648
Create Date: 2023-05-09 01:04:41.412563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = 'd1c2a425a8bc'
down_revision = '2b8c8ace3648'
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    # ### commands auto generated by Alembic - please adjust! ###
    # create table
    op.create_table('bot_texts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('bot_id', sa.Integer(), nullable=True),
                    sa.Column('text_id', sa.Integer(), nullable=True),
                    sa.Column('include_in_context',
                              sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
                    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_bot_texts_id'), 'bot_texts', ['id'], unique=False)

    # migrate all data into new table
    session.execute(text("""
    INSERT INTO 
        bot_texts (bot_id, text_id, include_in_context)
    SELECT bot_id, texts.id as text_id, uu.include_in_context FROM user_uploads uu INNER JOIN texts ON uu.id = texts.user_upload_id;
    """))

    # continue with Alembic commands
    op.drop_constraint('user_uploads_bot_id_fkey',
                       'user_uploads', type_='foreignkey')
    op.drop_column('user_uploads', 'include_in_context')
    op.drop_column('user_uploads', 'bot_id')
    # ### end Alembic commands ###

    # migrate all user texts to all bots for users


def downgrade() -> None:
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_uploads', sa.Column(
        'bot_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_uploads', sa.Column('include_in_context', sa.BOOLEAN(
    ), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.create_foreign_key('user_uploads_bot_id_fkey',
                          'user_uploads', 'bots', ['bot_id'], ['id'])
    op.add_column('texts', sa.Column('user_upload_id',
                  sa.INTEGER(), autoincrement=False, nullable=True))

    op.create_foreign_key('texts_user_upload_id_fkey',
                          'texts', 'user_uploads', ['user_upload_id'], ['id'])
    op.drop_index(op.f('ix_bot_texts_id'), table_name='bot_texts')
    op.drop_table('bot_texts')
    # ### end Alembic commands ###
