"""empty message

Revision ID: db09e4ed95f3
Revises: 2d5aac6d4f4e
Create Date: 2023-03-15 14:47:49.488977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db09e4ed95f3'
down_revision = '2d5aac6d4f4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_uploads', sa.Column('bot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_uploads', 'bots', ['bot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_uploads', type_='foreignkey')
    op.drop_column('user_uploads', 'bot_id')
    # ### end Alembic commands ###
