"""empty message

Revision ID: dea3b506543f
Revises: 9ab6e1541034
Create Date: 2023-05-01 17:14:39.828142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea3b506543f'
down_revision = '9ab6e1541034'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_authentications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.Column('authorization_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_authentications_id'), 'tool_authentications', ['id'], unique=False)
    op.alter_column('bot_tools', 'bot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bot_tools', 'tool_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bot_tools', 'tool_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bot_tools', 'bot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_tool_authentications_id'), table_name='tool_authentications')
    op.drop_table('tool_authentications')
    # ### end Alembic commands ###
