"""empty message

Revision ID: eaebae83559d
Revises: bdf804a235fc
Create Date: 2023-04-27 19:34:04.329615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from app.models import Persona, Bot


# revision identifiers, used by Alembic.
revision = 'eaebae83559d'
down_revision = 'bdf804a235fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('prompt', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('initial_message', sa.String()),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_personas_id'), 'personas', ['id'], unique=False)
    op.add_column('bots', sa.Column('persona_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bots', 'personas', ['persona_id'], ['id'])
    # ### end Alembic commands ###
    # add base persona
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    new_persona = Persona(
        name="Friendly Assistant",
        prompt="You are an AI assistant based on OpenAI's ChatGPT. You are designed to perform data search and retrieval from user uploaded files, and from the internet in general. You are kind and courteous.",
        initial_message="Hello! I'm Glyph! How can I help you today?"
    )
    session.add(new_persona)
    session.commit()
    session.refresh(new_persona)

    # add persona to all bots
    bots = session.query(Bot).all()
    for b in bots:
        b.persona_id = new_persona.id

    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bots', type_='foreignkey')
    op.drop_column('bots', 'persona_id')
    op.drop_index(op.f('ix_personas_id'), table_name='personas')
    op.drop_table('personas')
    # ### end Alembic commands ###
