"""empty message

Revision ID: edd300051710
Revises: 01bfe4c738d6
Create Date: 2023-03-15 19:52:18.937601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd300051710'
down_revision = '01bfe4c738d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('user_upload_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'texts', 'user_uploads', ['user_upload_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'texts', type_='foreignkey')
    op.drop_column('texts', 'user_upload_id')
    # ### end Alembic commands ###
